In [1]:
import tensorflow as tf

In [2]:
x = tf.range(12)

In [3]:
print(x)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)


In [4]:
y = tf.range(12, dtype=tf.float32)
print(y)

tf.Tensor([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.], shape=(12,), dtype=float32)


In [5]:
tf.size(y)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [6]:
y.shape

TensorShape([12])

In [7]:
X = tf.reshape(x, (3,4))
X

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])>

In [8]:
z = tf.zeros((3,4))
print(z)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)


In [9]:
b = tf.random.normal(shape=[3, 4])
print(b)

tf.Tensor(
[[ 1.6429918  -1.2119251  -0.7775339   0.15768674]
 [-0.876522    0.4977269  -0.62316793  0.51176894]
 [ 0.46794876  0.7713053   0.6336328   0.7631911 ]], shape=(3, 4), dtype=float32)


In [10]:
d = tf.constant([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(d)

tf.Tensor(
[[2 1 4 3]
 [1 2 3 4]
 [4 3 2 1]], shape=(3, 4), dtype=int32)
