In [1]:
import torch

In [2]:
x = torch.arange(12)

In [3]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [4]:
y = torch.arange(12, dtype=torch.float32)
print(y)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])


In [5]:
x.numel()

12

In [6]:
x.shape

torch.Size([12])

In [7]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.randn(3,4)

tensor([[ 0.1941, -1.7984,  1.7175,  0.2249],
        [-1.2742, -0.5469, -0.4269, -0.6625],
        [ 0.9242, -0.9733, -0.6419, -0.4470]])

In [11]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])